package dev.vellum.engine.layout;

import dev.vellum.engine.dom.Element;
import dev.vellum.engine.style.ComputedStyle;

import java.util.ArrayList;
import java.util.List;

/**
 * A layout box: the output of layout, read by paint, hit testing, scripts (getBoundingClientRect) and hosts (slot
 * positions).
 *
 * <p><b>Coordinates.</b> {@link #x}/{@link #y} are the border-box origin relative to the parent box's border-box
 * origin, ignoring the parent's scroll offset and transforms. Line fragments use the same space as children: relative
 * to this box's border-box origin. Where a box is on screen (scroll offsets, transforms) is
 * {@code paint.Coordinates}' business: it is the one mapping to and from viewport coordinates.
 *
 * <p>Absolutely and fixed positioned boxes stay children of their DOM parent's box (so paint order follows the
 * tree), with x/y converted into that parent's space; {@link #containingBlock} records what they are placed against,
 * and {@link #contentParent()} which scroll offsets and clips apply to them.
 */
public class Box {
    public enum Kind {
        /** A block container or flex/grid container generated by an element. */
        BLOCK,
        /** An anonymous block wrapping inline content (or loose text in a flex/grid container). */
        ANONYMOUS,
        /** A replaced element (img, item, slot, canvas, entity...). */
        REPLACED,
        /**
         * A ::before or ::after pseudo-element box: block-level or atomic ones are in their parent's
         * {@link #children}; inline ones, like {@link #INLINE} boxes, only own line fragments.
         */
        PSEUDO,
        /**
         * An inline element (span, a, b...). It is the element's {@code element.box} but is NOT in its parent's
         * {@link #children}: its content is painted from the parent's line fragments ({@link Fragment.InlineBox} and
         * text runs). Its parent is the box that owns those lines and its geometry is the bounding box of its
         * fragments, so it maps to the viewport like any box for scripts, focus rings and hosts.
         */
        INLINE
    }

    public final Kind kind;
    /** The generating element; for anonymous boxes, the element whose content it wraps; for pseudo boxes the host element. */
    public final Element element;
    public ComputedStyle style;
    public Box parent;
    public final List<Box> children = new ArrayList<>();

    /** Border-box position relative to the parent's border-box origin. */
    public float x, y;
    /** Border-box size. */
    public float width, height;
    public float marginTop, marginRight, marginBottom, marginLeft;
    public float borderTop, borderRight, borderBottom, borderLeft;
    public float paddingTop, paddingRight, paddingBottom, paddingLeft;

    /** Size of the scrollable overflow area measured from the padding-box origin (at least the padding box). */
    public float scrollWidth, scrollHeight;
    /** Offset of the first baseline from the border-box top, or NaN if the box has none. */
    public float baseline = Float.NaN;

    /** Line boxes, when this box establishes an inline formatting context; otherwise empty. */
    public final List<LineBox> lines = new ArrayList<>(0);
    /** True when this box is an inline-level box placed inside a line (inline-block, inline-flex, replaced inline). */
    public boolean atomicInline;
    /** Laid out by the absolute/fixed positioning pass. */
    public boolean outOfFlow;
    /**
     * For absolutely and fixed positioned boxes, the box they are placed against: the box of the nearest positioned
     * (for absolute) or transformed ancestor element, which is an {@link Kind#INLINE} box when that element is
     * inline; null for the viewport. Set by layout; null for in-flow boxes.
     */
    public Box containingBlock;

    public Box(Kind kind, Element element, ComputedStyle style) {
        this.kind = kind;
        this.element = element;
        this.style = style;
    }

    public void add(Box child) {
        child.parent = this;
        children.add(child);
    }

    // ---- Derived geometry ----

    public float contentX() { return borderLeft + paddingLeft; }
    public float contentY() { return borderTop + paddingTop; }
    public float contentWidth() { return Math.max(0, width - borderLeft - borderRight - paddingLeft - paddingRight); }
    public float contentHeight() { return Math.max(0, height - borderTop - borderBottom - paddingTop - paddingBottom); }
    public float paddingBoxWidth() { return Math.max(0, width - borderLeft - borderRight); }
    public float paddingBoxHeight() { return Math.max(0, height - borderTop - borderBottom); }
    public float marginBoxWidth() { return width + marginLeft + marginRight; }
    public float marginBoxHeight() { return height + marginTop + marginBottom; }

    /**
     * Whether this is its element's scroll container: an element's block or replaced box whose overflow is not
     * visible. The element holds the scroll offsets; anonymous, pseudo-element and inline boxes never scroll.
     */
    public boolean isScrollContainer() {
        return (kind == Kind.BLOCK || kind == Kind.REPLACED) && style.isScrollContainer();
    }

    /** Scroll offset applied to this box's children (zero unless it is a scroll container). */
    public float scrollLeft() { return isScrollContainer() ? element.scrollLeft() : 0; }
    public float scrollTop() { return isScrollContainer() ? element.scrollTop() : 0; }

    /** The largest scroll offsets the content allows: how far the scrollable overflow extends past the padding box. */
    public float maxScrollLeft() { return Math.max(0, scrollWidth - paddingBoxWidth()); }
    public float maxScrollTop() { return Math.max(0, scrollHeight - paddingBoxHeight()); }

    /**
     * The box whose content this box is placed in: its parent, except that an absolutely or fixed positioned box
     * belongs to its containing block's content (the block whose lines hold an inline containing block), or to the
     * viewport (null). The scroll offsets and clips of the ancestors it skips do not apply to it.
     */
    public Box contentParent() {
        if (!outOfFlow) return parent;
        Box cb = containingBlock;
        return cb != null && cb.kind == Kind.INLINE ? cb.parent : cb;
    }

    @Override
    public String toString() {
        return kind + (element != null ? " " + element : "") + String.format(" [%.1f,%.1f %.1fx%.1f]", x, y, width, height);
    }
}
